export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_SOME_OTHER_MOVIES = "GET_SOME_OTHER_MOVIES";
export const VERIFY_INITIAL_LIST_UPDATES_ARE_COMPLETE =
  "VERIFY_INITIAL_LIST_UPDATES_ARE_COMPLETE";
